### PR TITLE
ci: Bump golangci-lint to 1.45.2

### PR DESCRIPTION
**Pull request by ethan-lowman-dd**
Release Notes: Bump golangci-lint to 1.45.2

**Types of changes**:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

**Description of the changes being introduced by the pull request**:
Attempts to fix panic in golangci-lint (example: https://github.com/theupdateframework/go-tuf/runs/5889222812?check_suite_focus=true)
Related: https://github.com/golangci/golangci-lint/issues/2374, https://github.com/golangci/golangci-lint/issues/2649

**Please verify and check that the pull request fulfills the following requirements**:

- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

### CODE REVIEW

**Review by rdimitrov — APPROVED** [review]
I expected that dependabot would have handled this too, but it seems this is not the case.

**Comment by joshuagl** [comment]
> Would be nice to have @rdimitrov's approvals count for review requirements... :)

I'd second this motion. Should we vote on making him a maintainer?

**Comment by trishankatdatadog** [comment]
> I'd second this motion. Should we vote on making him a maintainer?

Eff yes

**Comment by asraa** [comment]
Let's also get one more approval here :)

**Review by joshuagl — APPROVED** [review]

**Pull request merged**
