### PR TITLE
fix(cmd): fix logging of help message

### PR DESCRIPTION
**Pull request by asraa**
Signed-off-by: Asra Ali <asraa@google.com>

Fixes comments of https://github.com/theupdateframework/go-tuf/pull/385

```
* fix(cmd): Prints help message on `Stdout` rather than `Stderr`
```

Please fill in the fields below to submit a pull request.  The more information that is provided, the better.

Fixes #<Issue>
Release Notes: 

**Types of changes**:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

**Description of the changes being introduced by the pull request**:

**Please verify and check that the pull request fulfills the following requirements**:

- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

### CODE REVIEW

**Review by trishankatdatadog — APPROVED** [review]

**Review by znewman01 — COMMENTED** [review]
While we're nitpicking what goes where...I build `tuf` at this PR and I see:

| cmd | output | stream | correct |
|-|-|-|-|
|`tuf` | usage | stdout | ❌<sup>*</sup>| 
| `tuf badcommand` | error | stderr| ✅| 
| `tuf --badarg` | usage | stderr| ✅| 
|`tuf help` |help |stderr |✅ |
|`tuf --help` | usage | stderr| ✅| 
|`tuf init --help` | help | stdout| ✅| 
|`tuf init --badarg` | usage | stdout| ❌ | 

<sup>*</sup> I think this one's debatable: is the user explicitly asking for the usage information? IMO no, they've invoked `tuf` incorrectly (if `tuf` had a no-args mode, it could be a correct usage)

Can we fix those too?

**Comment by mnm678** [comment]
> Any maintainer have any context why we're not using https://github.com/docopt/docopt.go? Was it too complex a dependency?

Looks like this decision was made in [2015](https://github.com/theupdateframework/go-tuf/commit/8fea2a2b962c0f55f66f385c9e935bce28208999) and not revisited (also, https://github.com/docopt/docopt.go was still pretty new in 2015). If a different library has features we need, I think we should switch.

**Comment by znewman01** [comment]
> Just looked into this further, since this was annoying to deal with:

Okay, I don't want to block this PR on you totally switching over our CLI engine.

> Any maintainer have any context why we're not using https://github.com/docopt/docopt.go? Was it too complex a dependency?

This is all speculation/hearsay, but IIRC Flynn was a big go-tuf user/contributor so a long time ago we bought into their go stack. However Flynn is sadly unmaintained so a lot of that is relatively dated.

I think a switch to more mainstream dependencies in place of the Flynn ones would be a good idea.

**Review by znewman01 — APPROVED** [review]

**Comment by asraa** [comment]
I'll create a follow up good first issue: it would be great to move over to another managing library then

**Review by znewman01 — APPROVED** [review]

**Pull request merged**
