### PR TITLE
Move CI to Github and add more Badges

### PR DESCRIPTION
**Pull request by shibumi**
This commit fixes CI via moving to Github Actions.
We do matrix checks from now on. This means go-tuf will be checked
against MacOS and Linux with Go version 1.13.x.
And because everybody likes badges, we are going to add a bunch of new
shiny badges to the project.

While doing this, I came across a few issues:

1. The tests fail on Go 1.14.x and Go 1.15.x on all plattforms
2. The tests fail on Windows

### CODE REVIEW

**Comment by shibumi** [comment]
Small note:

Some badges look broken in this PR, this is because the CI is not yet in the master branch of the go-tuf repository. If you merge this PR, the badges should be fine.

**Comment by shibumi** [comment]
Hi @titanous can we get @trishankatdatadog's PR merged first before this one here? I have the feeling, that I can maybe add Go 1.14 support for this one here, after applying Trishanks changes.

**Comment by trishankatdatadog** [comment]
> Hi @titanous can we get @trishankatdatadog's PR merged first before this one here? I have the feeling, that I can maybe add Go 1.14 support for this one here, after applying Trishanks changes.

It's a big one. Needs eyes from @erickt @raggi @joshuaseaton too 👀

**Comment by shibumi** [comment]
@erickt @trishankatdatadog Do you want to have a look? This PR adds Github Actions support + Integration tests for MacOS and Linux and support for tests on every Go long term support release (Go 1.13 - Go 1.15 at the moment). 

If you want to see how this will look like, have a look on my fork:

https://github.com/shibumi/go-tuf/actions/runs/273286943

**Review by erickt — APPROVED** [review]

**Review by trishankatdatadog — APPROVED** [review]

**Pull request merged**
