### PR TITLE
docs: removing hossein. It's been a pleasure

### PR DESCRIPTION
**Pull request by hosseinsia**
Please fill in the fields below to submit a pull request.  The more information that is provided, the better.

Fixes #<Issue>

Release Notes: 

**Types of changes**:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected). **Please ensure that your PR title** is a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) breaking change (with a `!`, as in `feat!: change foo`). 

**Description of the changes being introduced by the pull request**:

**Please verify and check that the pull request fulfills the following requirements**:

- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

### CODE REVIEW

**Review by trishankatdatadog — APPROVED** [review]
Thanks for your service!

**Comment by trishankatdatadog** [comment]
@hosseinsia would you please `--sign-off` your commit? The DCO Action above has details on how to do it.

**Comment by hosseinsia** [comment]
Trying to sign off after this commit gives me the following error:
```
git push --force-with-lease origin hosseinsia-remove-maintainer
ERROR: Permission to theupdateframework/go-tuf.git denied to hosseinsia.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by trishankatdatadog** [comment]
> Trying to sign off after this commit gives me the following error:

Ah, right, it must be because we removed access. Sorry about this: opened a new PR #430.

**Pull request closed without merging**
