### PR TITLE
Incorporate python-tuf v0.14 into the interoperability test suite

### PR DESCRIPTION
**Pull request by erickt**
This is a stack of patches that includes the latest published python-tuf into go-tuf's interopability test suite. This is to make sure that go-tuf can parse the metadata produced by python-tuf. It's split into 3 patches, to make it easier to review. The first, adds a generator script that produces the metadata in the second patch. Finally, the third incorporates this metadata into the test suite.

### CODE REVIEW

**Comment by trishankatdatadog** [comment]
Hmm, test failed, why? 👀

**Comment by erickt** [comment]
I'll do some investigation. I marked this as a draft PR so I can do some iteration on it.

**Comment by shibumi** [comment]
```
Run go test -race -covermode atomic -coverprofile='profile.cov' ./...
go: downloading gopkg.in/check.v1 v1.0.0-20200227125254-8fa46927fb4f
go: downloading github.com/niemeyer/pretty v0.0.0-20200227124842-a10e7caefd8e
go: downloading github.com/kr/text v0.1.0
ok  	github.com/theupdateframework/go-tuf	10.790s	coverage: 77.3% of statements
2020/09/28 22:35:22 generating /tmp/508640505
2020/09/28 22:35:22 generating /tmp/182601525

----------------------------------------------------------------------
FAIL: <autogenerated>:1: InteropSuite.TestPythonClientCompatibility

test case: python-tuf-v0.14 consistent-snapshot: false
step: 0
interop_test.go:168:
    c.Assert(err, IsNil)
... value client.ErrDownloadFailed = client.ErrDownloadFailed{File:"root.json", Err:util.ErrWrongVersion{Expected:0, Actual:1}} ("tuf: failed to download root.json: wrong version, expected 0 got 1")

OOPS: 33 passed, 1 FAILED
```

Looks like it's related to tuf-v0.14?

**Comment by shibumi** [comment]
@erickt @trishankatdatadog is it possible that we need to change the tests for this PR? Right now we only pull the latest tuf python package: https://github.com/theupdateframework/go-tuf/blob/master/.github/workflows/build.yml#L23

```
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade iso8601 requests securesystemslib six tuf
```

**Comment by mnm678** [comment]
Closing due to python-tuf updates

**Pull request closed without merging**
