### PR TITLE
Update MAINTAINERS

### PR DESCRIPTION
**Pull request by trishankatdatadog**

### CODE REVIEW

**Review by MDr164 — APPROVED** [review]

**Comment by MDr164** [comment]
Good to see the autoassign works, thanks Trishank for taking care of the update!

**Comment by trishankatdatadog** [comment]
@JustinCappos can you give @theupdateframework/go-tuf-maintainers admin access to the team itself?

**Review by MDr164 — APPROVED** [review]

**Comment by trishankatdatadog** [comment]
> Good to see the autoassign works, thanks Trishank for taking care of the update!

Sorry, last change, I swear

**Comment by trishankatdatadog** [comment]
> Githubs CI also seems to be down so technically we should also wait for that to pass even though none of the checks except DCO are mandatory.

There's also that too much bold heading in the Markdown, but I'll let someone else fix that now if they like...

**Review by mnm678 — APPROVED** [review]

**Review by MDr164 — APPROVED** [review]
I'm fine with the markdown as is

**Pull request merged**
