### PR TITLE
Delegation

### PR DESCRIPTION
**Pull request by SimonMen65**
This is a new delegation PR after rebased on master branch, hopefully this will work

### CODE REVIEW

**Comment by lukpueh** [comment]
Thanks for the PR, @SimonMen65! It would be helpful if you could add some information about the PR to the PR description. Same goes for commit message. The developer guidelines I shared with you before [have some good recommendations](https://github.com/secure-systems-lab/lab-guidelines/blob/master/commits.md) there.

**Comment by lukpueh** [comment]
Also, it looks like your local `delegation` branch as based off an outdated `master` branch (see conflict). Can you update your local `master` branch, rebase `delegation` on top of it and force push?

**Comment by SimonMen65** [comment]
@lukpueh Sry just saw ur message, can you check it again, I made some fixes yesterday. I think it's all updated now?

**Comment by lukpueh** [comment]
It does not look like the conflict is fixed. Do you see the note about "Conflicting files" on this page? Also, your PR includes unrelated commits now. I fear something went wrong during your rebase.

**Comment by trishankatdatadog** [comment]
@SimonMen65 Thanks for your continued work on this. I urge you to please take the time to learn how to use git and its features such as rebase. You will know when your PR is ready to review: you can see, for example, that the commits and file changes include only your work. Please practice on your own repository/fork if you must, and do not send another PR again until then. It's ok, we all learn, so please don't feel bad about this. Thanks again.

**Comment by SimonMen65** [comment]
@lukpueh Dear Luke, I think I fixed the conflict this time, it's a green check mark now! Can you further explain what do you mean by "unrelated commits". As for the comments of the past commits, I don't think I can change them but I will definitely follow the guidelines next time. Again Thanks for your patience.

**Comment by SimonMen65** [comment]
Another thing is the auto-runners/checks that shiburi deploys, I think they are lacking some configuration files since the error is "no such file ...."

**Pull request closed without merging**
