### PR TITLE
A first cut of automated releases using goreleaser

### PR DESCRIPTION
**Pull request by trishankatdatadog**
Thanks to #157 for inspiration (dropped SBOMs and signing now for simplicity).

Checklist:
- [x] Release client vs all
- [ ] Changelog (including a convention for marking PRs with backwards-incompatible changes)
- [ ] Prereleases
- [ ] Define convention to mark backwards-incompatible changes (despite using a MAJOR SemVer version of 0)
- [ ] Test with pushing a tag

Deferred:
* SBOMs
* Sign and add to Sigstore (besides gosumdb)

### CODE REVIEW

**Comment by rdimitrov** [comment]
@trishankatdatadog: Thanks again for working on that! 🥳 

About the 2nd point, Changelog, does what we have in https://github.com/theupdateframework/go-tuf/pull/215/file cover what you have in mind for stating any incompatible changes in the PR description or we need something more detailed?

**Comment by joshuagl** [comment]
Thank you for working on this! Which of the checklist items must happen before we merge this PR, and which can be filed as separate issues?

Do we need to tag current state before we merge this, so that there's a baseline to compare against?

> Checklist:
> 
> * [x]  Release client vs all
> * [ ]  Changelog (including a convention for marking PRs with backwards-incompatible changes)
> * [ ]  Prereleases

Can you expand on this a bit?

> * [ ]  Define convention to mark backwards-incompatible changes (despite using a MAJOR SemVer version of 0)

Isn't SemVer the convention, i.e., we have not made a commitment to any kind of stable API. We aim to highlight backwards incompatible changes in the Changlog, but until such a time as we make a 1.0 release those changes may happen at any arbitrary release.

> * [ ]  Test with pushing a tag

We can/should test on a personal fork.

**Comment by trishankatdatadog** [comment]
> About the 2nd point, Changelog, does what we have in #215 cover what you have in mind for stating any incompatible changes in the PR description or we need something more detailed?

I suppose it does if every PR's description in its entirety is copied into the changelog, no?

**Comment by trishankatdatadog** [comment]
> Do we need to tag current state before we merge this, so that there's a baseline to compare against?

Yes we should

> Can you expand on this a bit? Is the goal to be able to make pre-releases with a tagging convention?

Yes

> Isn't SemVer the convention, i.e., we have not made a commitment to any kind of stable API. We aim to highlight backwards incompatible changes in the Changlog, but until such a time as we make a 1.0 release those changes may happen at any arbitrary release.

The last bit must have slipped my mind. So, perfect, we can stick to 0.MINOR.PATCH for now and still make breaking releases

> We can/should test on a personal fork.

👍🏽 

So are we nearly done here?

**Review by joshuagl — COMMENTED** [review]
I think we're nearly done here. Someone (happy to do it Thursday/Friday if no one else volunteers) should tag the current state (as 0.1.0 or some other version?) and then we can merge this.

cc @theupdateframework/go-tuf-maintainers please take a look!

**Review by mnm678 — APPROVED** [review]

**Comment by rdimitrov** [comment]
> > About the 2nd point, Changelog, does what we have in #215 cover what you have in mind for stating any incompatible changes in the PR description or we need something more detailed?
> 
> I suppose it does if every PR's description in its entirety is copied into the changelog, no?

@trishankatdatadog - Oh, I see. Well, from what I found `goreleaser` uses only the commit messages. There's this too - [buchanae/github-release-notes](https://github.com/buchanae/github-release-notes), which can replace the commit messages with PR titles instead, but it still doesn't solve our goal. 

A possible solution is to leverage the [`groups`](https://goreleaser.com/customization/changelog/) feature for composing the changelog. If we enforce people to use a dedicated tag word/phrase in their commit message when there's a breaking change, this will be caught up by `goreleaser` and will create a dedicated section in the changelog with all commits that supposedly introduce breaking changes.

**Comment by trishankatdatadog** [comment]
Ok, sounds good. @joshuagl @rdimitrov can you both pls help finish this PR? I'm afraid I don't have the time this week or the next...

**Comment by joshuagl** [comment]
I just tagged [v0.1.0](https://github.com/theupdateframework/go-tuf/releases/tag/v0.1.0). @rdimitrov and/or myself will finish up this PR early next week.

**Pull request closed without merging**
