### PR TITLE
docs: added myself (kommendorkapten) as a maintainer

### PR DESCRIPTION
**Pull request by kommendorkapten**
cc @mnm678 @znewman01

### CODE REVIEW

**Comment by asraa** [comment]
I think it's also time I stepped down - Fredrik you can take my place :D and move me off the list in this change

cc @theupdateframework/go-tuf-maintainers

**Comment by kommendorkapten** [comment]
@asraa sure, but it makes me sad :(

**Review by znewman01 — APPROVED** [review]
@asraa thanks for all your work on this project!

**Review by mnm678 — APPROVED** [review]
@kommendorkapten has been an active contributor and user, and I support this addition.

**Review by znewman01 — APPROVED** [review]

**Comment by kommendorkapten** [comment]
Thanks for all the work @asraa ❤️

**Review by joshuagl — APPROVED** [review]
I completely support this change. Welcome @kommendorkapten, thank you for your interest in maintaining go-tuf. @asraa, thanks for all the work on go-tuf!

My last commits were in November '22, so it's probably time I rescinded my maintainer bit too...

**Comment by trishankatdatadog** [comment]
Thank you, @asraa, for all your great work on go-tuf, and @kommendorkapten, for taking up the mantle.

**Review by trishankatdatadog — APPROVED** [review]

**Comment by asraa** [comment]
Thank YOU all!!

**Pull request merged**
