### PR TITLE
fix: update leveldb dependency

### LINKED ISSUE #349: update leveldb with fsync fix
See: https://github.com/syndtr/goleveldb/issues/335

" leveldb: manifest corrupted (field 'comparer'): missing [file=MANIFEST-000006] "

We have seen this issue where a reboot/crash of the tuf client causes the leveldb to be corrupted. Updating the goleveldb version to the latest suggests it will fix this.

### PR DESCRIPTION
**Pull request by mfmarche**
Update https://github.com/syndtr/goleveldb dependency

Fixes #349

**Types of changes**:

- [X] Bug fix (non-breaking change which fixes an issue)
- [  ] New feature (non-breaking change which adds functionality)
- [  ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

**Description of the changes being introduced by the pull request**:

Updates the dependency to  https://github.com/syndtr/goleveldb. leveldb required an fsync after creation of the MANIFEST file.
**Please verify and check that the pull request fulfills the following requirements**:

- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

### CODE REVIEW

**Comment by joshuagl** [comment]
Thank you for submitting this fix @mfmarche! The CI appears to be failing due to a missing entry in go.sum https://github.com/theupdateframework/go-tuf/runs/7641572216?check_suite_focus=true#step:6:27 would it be possible to address that? 

Also, the DCO check failed. Could you `git commit --signoff` (or `git commit -s`) to include a `signed-off-by` entry in your commits? (You'll want to fix the existing commit before you add new ones to address the failing CI, you can do that with `git commit --amend -s` on the branch you used).

**Comment by mfmarche** [comment]
hi @joshuagl thanks for the review. I made the changes and signed off. thank you.

**Review by joshuagl — APPROVED** [review]
LGTM, thanks again @mfmarche

**Comment by joshuagl** [comment]
Could someone give this a second +1? @znewman01 @asraa @mnm678

**Review by znewman01 — APPROVED** [review]

**Pull request merged**
