### PR TITLE
Move delegations iterator to internal package

### PR DESCRIPTION
**Pull request by ethan-lowman-dd**
This PR moves the delegations iterator from the client package (private) to public internal packages. This will allow us to reuse the iterator in other packages when we implement writing to delegated targets.

Split into a separate PR to keep review easy, as this is mostly copy & paste and capitalization changes.

### CODE REVIEW

**Comment by trishankatdatadog** [comment]
@hosseinsia

**Comment by trishankatdatadog** [comment]
@raphaelgavache

**Review by raphaelgavache — APPROVED** [review]
lgtm

**Review by hosseinsia — APPROVED** [review]
LGTM.

**Review by asraa — APPROVED** [review]

**Pull request merged**
