### PR TITLE
refactor: move delegations to pkg/ for export

### PR DESCRIPTION
**Pull request by asraa**
Signed-off-by: Asra Ali <asraa@google.com>

Moving the delegation iterator to pkg/ so that the iterator can be accessed in external projects that want to iterate over the delegations and read information like roles/thresholds from delegations.

### CODE REVIEW

**Review by ethan-lowman-dd — DISMISSED** [review]

**Review by trishankatdatadog — DISMISSED** [review]

**Comment by trishankatdatadog** [comment]
@asraa is it possible to sign your git commits? If not easy to do right now, let me make a workaround.

**Comment by asraa** [comment]
> @asraa is it possible to sign your git commits? If not easy to do right now, let me make a workaround.

Interesting, I wonder why they're not! I use -s on commit, let me see

**Comment by asraa** [comment]
All signed :)
Although I'm not totally sure what the point of gpg signing is on GH -- only gh is verifying the signed commits, and if so, then why not trust gh login with 2FA in the organization?

**Comment by trishankatdatadog** [comment]
Yeah, let me turn off that requirement, thanks!

**Review by trishankatdatadog — APPROVED** [review]

**Comment by asraa** [comment]
friendly ping @ethan-lowman-dd

**Review by ethan-lowman-dd — APPROVED** [review]

**Pull request merged**
