### PR TITLE
chore: remove GITHUB_TOKEN from arnested/go-version-action 

### PR DESCRIPTION
**Pull request by arnested**
Hi,

I'm the author of [arnested/go-version-action](https://github.com/marketplace/actions/go-version-action).

The action doesn't need a GITHUB_TOKEN anymore.

Instead of getting the Go releases from git tags using GitHub's API (and thus needing the token to avoid being rate limited) it pulls the versions from https://go.dev/dl/?mode=json&include=all.

### CODE REVIEW

**Review by rdimitrov — APPROVED** [review]
@arnested - Thank you for reaching out and for addressing that change in go-tuf too! 👍

**Comment by arnested** [comment]
> @arnested - Thank you for reaching out and for addressing that change in go-tuf too! +1

There were only five projects using GITHUB_TOKEN (not counting my own) so I thought it was a good opportunity to be helpful. Don't expect the same level of service if this ever gains widespread popularity :stuck_out_tongue: 

> edit: Forgot to say that I'd suggest to reword the commit message to comply with the [conventional commit guideline](https://www.conventionalcommits.org/en/v1.0.0/), otherwise the linter GitHub action will probably fail +1

Fixed :+1:

**Review by rdimitrov — DISMISSED** [review]

**Review by asraa — DISMISSED** [review]
Thanks! 

This supersedes https://github.com/theupdateframework/go-tuf/pull/260/ too

**Comment by asraa** [comment]
@hosseinsia could you PTAL? should be easy

**Review by znewman01 — APPROVED** [review]

**Review by znewman01 — APPROVED** [review]

**Review by joshuagl — APPROVED** [review]
Thanks so much for submitting this @arnested !

**Review by mnm678 — APPROVED** [review]

**Pull request merged**
